; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Guiche"
#define MyAppVersion "1.3"
#define MyAppPublisher "Maurinsoft"
#define MyAppURL "http://maurinsoft.com.br"
#define MyAppExeName "Guiche.exe"

[Setup]
AppId={{472790A2-45A6-442C-A62A-4992BD141B37}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\Guiche
DisableProgramGroupPage=yes
OutputBaseFilename=setup_guiche130
Compression=lzma
SolidCompression=yes
; Necessário para gravar em C:\
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\projetos\maurinsoft\fila\Guiche\Guiche.exe"; DestDir: "{app}"; Flags: ignoreversion
; Copia o arquivo global.cfg APENAS se a configuração for coletiva
Source: "D:\projetos\maurinsoft\fila\Guiche\global.cfg"; DestDir: "C:\guiche"; Flags: ignoreversion; Check: IsColetiva

[Dirs]
; Cria C:\guiche somente se for configuração coletiva
Name: "C:\guiche"; Check: IsColetiva

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
var
  PageConfig: TWizardPage;
  rbIndividual, rbColetiva: TRadioButton;

function IsColetiva: Boolean;
begin
  // Verdadeiro se o usuário escolher "Coletiva"
  Result := (rbColetiva <> nil) and rbColetiva.Checked;
end;

procedure InitializeWizard;
begin
  // Página personalizada logo após Tarefas (pode mudar para outra etapa se preferir)
  PageConfig := CreateCustomPage(wpSelectTasks,
    'Tipo de configuração',
    'Escolha o modo de configuração da aplicação:');

  rbIndividual := TNewRadioButton.Create(PageConfig);
  rbIndividual.Parent := PageConfig.Surface;
  rbIndividual.Caption := 'Usuário ';
  rbIndividual.Checked := True;

  rbColetiva := TNewRadioButton.Create(PageConfig);
  rbColetiva.Parent := PageConfig.Surface;
  rbColetiva.Caption := 'Global';
  rbColetiva.Top := rbIndividual.Top + rbIndividual.Height + ScaleY(8);
end;
