; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Fila"
#define MyAppVersion "4.02"
#define MyAppPublisher "maurinsoft"
#define MyAppURL "http://maurinsoft.com.br"
#define MyAppExeName "Fila.exe"
#define MySrvExeName "srvfalar.exe"

[Setup]
AppId={{15E35926-C8B9-4F48-BA73-8986FF92FAD2}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=fila_setup_402
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Types]
Name: "Elgin"; Description:  {cm:T_Elgin}
Name: "Pos58"; Description: {cm:T_Pos58}
Name: "Pos5811"; Description: {cm:T_Pos5811}
Name: "Fila"; Description: {cm:T_Fila}

[Components]
Name: "File"; Description: "Arquivos do Fila"; Types: Fila;
Name: "Elgin"; Description: "Instalação do Fila com Elgin"; Types:  Fila  Elgin;
Name: "Pos58"; Description: "Instalação do Fila com POS58"; Types:  Fila Pos58;
Name: "Pos5811"; Description: "Instalação do Fila com POS5811"; Types:  Fila Pos5811;

[CustomMessages]
T_Elgin=Elgin
TD_Elgin=Instalação padrão do fila com drivers do Elgin i9
T_Pos58=Pos58
TD_Pos58=Instalação padrão do fila com drivers do Pos58
T_Pos5811=Pos5811
TD_Pos5811=Instalação padrão do fila com drivers do Pos5811
T_Fila=Fila
TD_Fila=Instalação padrão do fila sem drivers do fabricante de impressora

[Code]
#define MSIDT_CustomType "Whatever"
#include "DescriptiveTypes.isi"
procedure InitializeWizard();
begin
 InitializeDescriptiveTypes();
end;

[Files]
Source: "D:\projetos\maurinsoft\fila\Fila\Fila.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\Fila\srvfalar.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\Fila\libcrypto-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\Fila\libssl-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\Fila\Win32OpenSSL_Light-3_5_2.msi"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\drivers\Elgin i9\ELGIN Printer Driver_v-1.6.6.exe"; DestDir: "{app}"; Components: Elgin;
Source: "D:\projetos\maurinsoft\fila\drivers\POS58\POS Printer Driver Setup .exe"; DestDir: "{app}"; Components: Pos58;
Source: "D:\projetos\maurinsoft\fila\drivers\POS5811-DD\POS Printer Driver Setup .exe"; DestDir: "{app}"; Components: Pos5811;

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{commonstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Comment: "Inicia automaticamente com o Windows"
Name: "{commonstartup}\srvfalar"; Filename: "{app}\{#MySrvExeName}"; Comment: "Inicia automaticamente com o Windows"

[Run]
Filename: "{app}\ELGIN Printer Driver_v-1.6.6.exe"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Components: Elgin;
Filename: "{app}\POS Printer Driver Setup .exe"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Components: Pos58; 
Filename: "{app}\POS Printer Driver Setup .exe"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Components: Pos5811; 
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#MySrvExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
