; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PainelDesk"
#define MyAppVersion "1.22"
#define MyAppPublisher "maurinsoft"
#define MyAppURL "http://maurinsoft.com.br"
#define MyAppExeName "PainelDesk.exe"
#define MySrvExeName "srvfalar.exe"

[Setup]
AppId={{15E35922-C8B1-4F49-BC72-8986FF92FBD2}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DisableProgramGroupPage=yes
OutputBaseFilename=paineldesk_setup_122
Compression=lzma
SolidCompression=yes

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Types]
Name: "PAINELDESK"; Description: {cm:T_PAINELDESK}

[Components]
Name: "PAINELDESK"; Description: "Arquivos do PAINELDESK"; Types: PAINELDESK;


[CustomMessages]
T_PAINELDESK=PAINELDESK
TD_PAINELDESK=Instalação padrão do PainelDESKTOP

[Code]
#define MSIDT_CustomType "Whatever"
#include "DescriptiveTypes.isi"
procedure InitializeWizard();
begin
 InitializeDescriptiveTypes();
end;

[Files]
Source: "D:\projetos\maurinsoft\fila\PainelDesk\paineldesk.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\PainelDesk\srvfalar.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\PainelDesk\libssl-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\PainelDesk\libcrypto-3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projetos\maurinsoft\fila\PainelDesk\Win32OpenSSL_Light-3_5_2.msi"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{commonstartup}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Comment: "Inicia automaticamente com o Windows"
Name: "{commonstartup}\srvfalar"; Filename: "{app}\{#MySrvExeName}"; Comment: "Inicia automaticamente com o Windows"


[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\{#MySrvExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
